### ISSUE TITLE
lazy io

### ISSUE THREAD

**Issue by michaelt** [kvafy/extension-fixer#1]
This is a silly remark coming from left field, but I was just searching github for examples of the use of `mapM` while trying to think about writing a 'streaming io' tutorial, and happened on this program. `mapM`, `replicateM`, `sequence` and `traverse` are typical things streaming io libraries try to replace.

So I tried it and sure enough one of the typical lazy-io troubles was easy enough to generate on os x if I had enough files in the directory

```
   -- $ ./extensionfixer .
   -- extensionfixer: 327.jpg: openBinaryFile: resource exhausted (Too many open files)
```

(I think os x is stingier than linux so this might not be easy to replicate.)

The trouble is that `identifyFormats` or `mapM (\fp -> do {ff <- identifyFormatIO fp; return (fp, ff)})` wants to open each file in the list, and then returns the list with their contents. In the meantime all the handles are open simultaneously. 

So I thought I would try a minimal rewrite of `main` using the `streaming` library. This is the library I am trying to explain, but it would be the same with e.g. `pipes`, only sometimes instead of `f (g x)` you would write `g x >-> f`)  The resulting program, for what it's worth https://gist.github.com/michaelt/d6dde573fa33ca4b15b930ec318d5bef only opens one file at at time.  The changes come on line 86 and later.

The only part that wasn't really simple was maintaining a count of the original files, before filtering out the ones with a wrong extension. The program should in principle use less memory, though this desired result necessarily accumulates all the bad files and _then_ asks the user if she wants to make the repairs, so there is some accumulation anyway. In any case, I thought the results of my little effort might amuse you.

**Comment by kvafy** [comment]
The remark is definitely very much appreciated, thank you!

As you can probably tell by the code quality, this is one of my first Haskell projects and, coming from imperative background, I am just in the process of getting my head around the different style of thinking with monads, monad transformers, laziness and other aspects. I would think that the IO operations could be serialized in a simpler (although less generic) fashion using just standard Prelude primitives. For example, would the following code work?

```
identifyFormats = foldM (\res fp -> do
                           ff <- identifyFormatIO fp
                           return $ (fp,ff):res)
                         []
```

If my understanding is correct, then the folding function will "unwrap" the value/outcome of the previous IO actions into `res`, thereby the IO actions that produce `res` are already executed at this point, and add `identifyFormatIO` action for the current `fp`. Or more precisely, the `identifyFormats` function just produces a composite IO action and when this action is executed, the encapsulated `identifyFormatIO` actions happen in serialized fashion.

**Comment by michaelt** [comment]
Actually my solution is overkill anyway. The original program seems to work fine if I am more cautious in the implementation of `identifyFormatIO` 

```
import Control.Exception (evaluate)
import qualified System.IO as IO

identifyFormatIO :: FilePath -> IO (Maybe FileFormat)
identifyFormatIO file = do
  h <- IO.openFile file IO.ReadMode
  bytes <- B.hGetContents h
  fmt <- evaluate $ identifyFormat (B.unpack bytes)
  -- evaluate may do no more than a little strictness would somewhere in here
  IO.hClose h
  return fmt
```

The trouble, or part of the trouble, with the original program was that it used (bytestring) `readFile`. So it left handles open until the garbage collector realized it didn't need to refer back to them.  Here I make (fairly) sure that everything I need is done and then close the handle explicitly.  Since `getContents` is lazy, this could still be a problem if we need the contents later, but here we just need to calculate the format from it.

So it's not the best example for my purposes....

Your version with `foldM` seems to behave similarly.  It's a little hard to analyze since `foldM` is defined as `foldlM` which involves assembling a complex function and then (in your application) applying it to `[]`

```
 foldlM f z0 xs = foldr f' return xs z0 
    where f' x k z = f z x >>= k
```

I assume this means, among other things, that I can only inspect the first element of the list if the rest of it has also been calculated by repeatedly prepending to []. This is highly desirable where lazy io is a problem, but that seems not really to be an issue here ... once we get slightly more 'professional' (as Oleg K. woulds say) with the use of file handles. Here's the last version I was using fwiw https://gist.github.com/michaelt/2997883f9108cea0703dd7aaa6ddca93

**Comment by kvafy** [comment]
You are right, using _strace_ I can see that my proposed solution is no better than the initial code - in both cases there is a sequence of `open` system calls followed by a sequence of `close` calls, so at some point during execution all the files are opened simultaneously.
Your solution with `evaluate` and explicit file handle operations has nice pairs of `open` / `close` invocations in a truly sequential manner.

Thank you for all the help.
